package $PACKAGE_NAME.util

/**
 * KeyCodes - JavaScript
 */
object KeyCode {
    const val KEY_CODE_NO_KEYCODE = 0
    const val KEY_CODE_BREAK = 3
    const val KEY_CODE_BACKSPACE_DELETE = 8
    const val KEY_CODE_TAB = 9
    const val KEY_CODE_CLEAR = 12
    const val KEY_CODE_ENTER = 13
    const val KEY_CODE_SHIFT = 16
    const val KEY_CODE_CTRL = 17
    const val KEY_CODE_ALT = 18
    const val KEY_CODE_PAUSE_BREAK = 19
    const val KEY_CODE_CAPS_LOCK = 20
    const val KEY_CODE_HANGUL = 21
    const val KEY_CODE_HANJA = 25
    const val KEY_CODE_ESCAPE = 27
    const val KEY_CODE_CONVERSION = 28
    const val KEY_CODE_NON_CONVERSION = 29
    const val KEY_CODE_SPACEBAR = 32
    const val KEY_CODE_PAGE_UP = 33
    const val KEY_CODE_PAGE_DOWN = 34
    const val KEY_CODE_END = 35
    const val KEY_CODE_HOME = 36
    const val KEY_CODE_LEFT_ARROW = 37
    const val KEY_CODE_UP_ARROW = 38
    const val KEY_CODE_RIGHT_ARROW = 39
    const val KEY_CODE_DOWN_ARROW = 40
    const val KEY_CODE_SELECT = 41
    const val KEY_CODE_PRINT = 42
    const val KEY_CODE_EXECUTE = 43
    const val KEY_CODE_PRINT_SCREEN = 44
    const val KEY_CODE_INSERT = 45
    const val KEY_CODE_DELETE = 46
    const val KEY_CODE_HELP = 47
    const val KEY_CODE_0 = 48
    const val KEY_CODE_1 = 49
    const val KEY_CODE_2 = 50
    const val KEY_CODE_3 = 51
    const val KEY_CODE_4 = 52
    const val KEY_CODE_5 = 53
    const val KEY_CODE_6 = 54
    const val KEY_CODE_7 = 55
    const val KEY_CODE_8 = 56
    const val KEY_CODE_9 = 57
    const val KEY_CODE_COLON = 58 // :
    const val KEY_CODE_SEMICOLON_FIREFOX_OR_EQUALS = 59
    const val KEY_CODE_LESS_THAN = 60 // <
    const val KEY_CODE_EQUALS_FIREFOX = 61
    const val KEY_CODE_SS = 63
    const val KEY_CODE_AT_SIGN_FIREFOX = 64
    const val KEY_CODE_A = 65
    const val KEY_CODE_B = 66
    const val KEY_CODE_C = 67
    const val KEY_CODE_D = 68
    const val KEY_CODE_E = 69
    const val KEY_CODE_F = 70
    const val KEY_CODE_G = 71
    const val KEY_CODE_H = 72
    const val KEY_CODE_I = 73
    const val KEY_CODE_J = 74
    const val KEY_CODE_K = 75
    const val KEY_CODE_L = 76
    const val KEY_CODE_M = 77
    const val KEY_CODE_N = 78
    const val KEY_CODE_O = 79
    const val KEY_CODE_P = 80
    const val KEY_CODE_Q = 81
    const val KEY_CODE_R = 82
    const val KEY_CODE_S = 83
    const val KEY_CODE_T = 84
    const val KEY_CODE_U = 85
    const val KEY_CODE_V = 86
    const val KEY_CODE_W = 87
    const val KEY_CODE_X = 88
    const val KEY_CODE_Y = 89
    const val KEY_CODE_Z = 90
    const val KEY_CODE_WINDOWS_KEY_LEFT_CHROMEBOOK_SEARCH_KEY = 91 //KEY / LEFT ⌘ / CHROMEBOOK SEARCH KEY
    const val KEY_CODE_RIGHT_WINDOW_KEY = 92
    const val KEY_CODE_WINDOWS_MENU_RIGHT = 93 // WINDOWS_MENU / RIGHT ⌘
    const val KEY_CODE_SLEEP = 95
    const val KEY_CODE_NUMPAD_0 = 96
    const val KEY_CODE_NUMPAD_1 = 97
    const val KEY_CODE_NUMPAD_2 = 98
    const val KEY_CODE_NUMPAD_3 = 99
    const val KEY_CODE_NUMPAD_4 = 100
    const val KEY_CODE_NUMPAD_5 = 101
    const val KEY_CODE_NUMPAD_6 = 102
    const val KEY_CODE_NUMPAD_7 = 103
    const val KEY_CODE_NUMPAD_8 = 104
    const val KEY_CODE_NUMPAD_9 = 105
    const val KEY_CODE_MULTIPLY = 106
    const val KEY_CODE_ADD = 107
    const val KEY_CODE_NUMPAD_PERIOD_FIREFOX = 108
    const val KEY_CODE_SUBTRACT = 109
    const val KEY_CODE_DECIMAL_POINT = 110
    const val KEY_CODE_DIVIDE = 111
    const val KEY_CODE_F1 = 112
    const val KEY_CODE_F2 = 113
    const val KEY_CODE_F3 = 114
    const val KEY_CODE_F4 = 115
    const val KEY_CODE_F5 = 116
    const val KEY_CODE_F6 = 117
    const val KEY_CODE_F7 = 118
    const val KEY_CODE_F8 = 119
    const val KEY_CODE_F9 = 120
    const val KEY_CODE_F10 = 121
    const val KEY_CODE_F11 = 122
    const val KEY_CODE_F12 = 123
    const val KEY_CODE_F13 = 124
    const val KEY_CODE_F14 = 125
    const val KEY_CODE_F15 = 126
    const val KEY_CODE_F16 = 127
    const val KEY_CODE_F17 = 128
    const val KEY_CODE_F18 = 129
    const val KEY_CODE_F19 = 130
    const val KEY_CODE_F20 = 131
    const val KEY_CODE_F21 = 132
    const val KEY_CODE_F22 = 133
    const val KEY_CODE_F23 = 134
    const val KEY_CODE_F24 = 135
    const val KEY_CODE_F25 = 136
    const val KEY_CODE_F26 = 137
    const val KEY_CODE_F27 = 138
    const val KEY_CODE_F28 = 139
    const val KEY_CODE_F29 = 140
    const val KEY_CODE_F30 = 141
    const val KEY_CODE_F31 = 142
    const val KEY_CODE_F32 = 143
    const val KEY_CODE_NUM_LOCK = 144
    const val KEY_CODE_SCROLL_LOCK = 145
    const val KEY_CODE_AIRPLANE_MODE = 151
    const val KEY_CODE_CARET = 160 // ^
    const val KEY_CODE_EXCLAMATION = 161
    const val KEY_CODE_ARABIC_SEMICOLON = 162 // ؛ (ARABIC SEMICOLON)
    const val KEY_CODE_HASH_SIGN = 163 // #
    const val KEY_CODE_DOLLAR_SIGN = 164 // $
    const val KEY_CODE_U_SIGN = 165 // Ù
    const val KEY_CODE_PAGE_BACKWARD = 166
    const val KEY_CODE_PAGE_FORWARD = 167
    const val KEY_CODE_REFRESH = 168
    const val KEY_CODE_CLOSING_PAREN_AZERTY = 169
    const val KEY_CODE_ASTERISK = 170 // *
    const val KEY_CODE_TILDE_PLUS_ASTERISK_KEY = 171 // ~+*
    const val KEY_CODE_HOME_KEY = 172
    const val KEY_CODE_MINUS_FIREFOX_MUTE_UNMUTE = 173 // (FIREFOX), MUTE/UNMUTE
    const val KEY_CODE_DECREASE_VOLUME_LEVEL = 174
    const val KEY_CODE_INCREASE_VOLUME_LEVEL = 175
    const val KEY_CODE_NEXT = 176
    const val KEY_CODE_PREVIOUS = 177
    const val KEY_CODE_STOP = 178
    const val KEY_CODE_PLAY_PAUSE = 179
    const val KEY_CODE_E_MAIL = 180
    const val KEY_CODE_MUTE_UNMUTE_FIREFOX = 181
    const val KEY_CODE_DECREASE_VOLUME_LEVEL_FIREFOX = 182
    const val KEY_CODE_INCREASE_VOLUME_LEVEL_FIREFOX = 183
    const val KEY_CODE_SEMI_COLON_N = 186 // SEMI-COLON / Ñ
    const val KEY_CODE_EQUAL_SIGN = 187
    const val KEY_CODE_COMMA = 188
    const val KEY_CODE_DASH = 189
    const val KEY_CODE_PERIOD = 190
    const val KEY_CODE_FORWARD_SLASH_C = 191 // SLASH / Ç
    const val KEY_CODE_GRAVE_ACCENT_N_AE_O = 192 // GRAVE ACCENT / Ñ / Æ / Ö
    const val KEY_CODE_QUESTION_MARK_O = 193 // ?, / OR °
    const val KEY_CODE_NUMPAD_PERIOD_CHROME = 194
    const val KEY_CODE_OPEN_BRACKET = 219
    const val KEY_CODE_BACK_SLASH = 220
    const val KEY_CODE_CLOSE_BRACKET_A = 221 // CLOSE BRACKET / Å
    const val KEY_CODE_SINGLE_QUOTE_O_A = 222 // SINGLE QUOTE / Ø / Ä
    const val KEY_CODE_BACK_QUOTE = 223 // `
    const val KEY_CODE_LEFT_OR_RIGHT_COMMAND_KEY = 224 // LEFT OR RIGHT ⌘ KEY (FIREFOX)
    const val KEY_CODE_ALT_GR = 225
    const val KEY_CODE_GIT_LEFT_BACK_SLASH = 226 // < /GIT >, LEFT BACK SLASH
    const val KEY_CODE_GNOME_COMPOSE_KEY = 230
    const val KEY_CODE_C_SPECIAL = 231 // Ç
    const val KEY_CODE_XF86FORWARD = 233
    const val KEY_CODE_XF86BACK = 234
    const val KEY_CODE_NO_CONVERSION = 235
    const val KEY_CODE_ALPHANUMERIC = 240
    const val KEY_CODE_HIRAGANA_KATAKANA = 242
    const val KEY_CODE_HALF_WIDTH_FULL_WIDTH = 243
    const val KEY_CODE_KANJI = 244
    const val KEY_CODE_UNLOCK_TRACKPAD_CHROME_EDGE = 251 // UNLOCK TRACKPAD (CHROME/EDGE)
    const val KEY_CODE_TOGGLE_TOUCHPAD = 255
}
